# Generated by Django 5.0.2 on 2024-03-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="details",
            name="points",
            field=models.CharField(max_length=255),
        ),
    ]
