# Generated by Django 5.0.2 on 2024-03-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_details_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="details",
            name="detailsTitle",
            field=models.CharField(default="sample", max_length=255),
            preserve_default=False,
        ),
    ]
